### ISSUE TITLE
[BUG]: doesn't filter text with parenthesis

### ISSUE THREAD

**Issue by ThomasVermes** [cchmc/redcap-em-report-filters#16]
Dear Joshua,

I'm texting you here since you might have not seen this post where the bug is described
https://redcap.vumc.org/community/post.php?id=240135

best
Thomas

**Comment by JoshuaFortriede** [comment]
@ThomasVermes, yes I saw that. I have just gotten time to work on this and I believe I have a fix that is close to being able to be released. I am doing final testing.

**Comment by JoshuaFortriede** [comment]
I have submitted 1.0.7 which I believe fixes this issue. Please let me know if you still see the issue.
